function task= read_csv_fmri(dfile)
    %read the csv data files generated by prolific and output the information
    %
    data=readtable(dfile);
    task.subname=extractAfter(extractBefore(dfile,'/Behaviour'),'raw_data/');

    task.choice=2-data.choice(~isnan(data.choice));%1for chosing opt1 0for chosing opt2
    task.opt1pos=data.opt1pos(~isnan(data.opt1pos));
    task.total_money=data.total_money(~isnan(data.total_money));
    task.trialN=data.trials_thisTrialN(~isnan(data.trials_thisTrialN));
    task.trial_idx=data.trials_thisIndex(~isnan(data.trials_thisIndex));
    task.correctopt=data.correctopt(~isnan(data.correctopt));
    task.str_opt1_out=data.opt1_out(~cellfun('isempty',data.opt1_out));
    task.str_opt2_out=data.opt2_out(~cellfun('isempty',data.opt2_out));
    task.str_blockN=data.blockn(~cellfun('isempty',data.blockn));
    task.chosenside=data.feedback_pos(~isnan(data.feedback_pos))+0.5;
    task.correct=data.correct(~isnan(data.correct));
    task.order=data.order(~isnan(data.order));
    task.resp=data.key_resp_choice_keys(~isnan(data.key_resp_choice_keys));
    task.rt=data.key_resp_choice_rt(~isnan(data.key_resp_choice_rt));
    task.diff=data.diff(~isnan(data.diff));



    task.TR_choice=data.TR_choice(~isnan(data.TR_choice));
    task.TR_monitor=data.TR_monitor(~isnan(data.TR_monitor));
    task.TR_feedback1=data.TR_feedback1(~isnan(data.TR_feedback1));
    task.TR_feedback2=data.TR_feedback2(~isnan(data.TR_feedback2));
    task.TR_ITI=data.TR_ITI(~isnan(data.TR_ITI));



    for j=1:size(task.str_opt1_out,1)
        tmp=extractAfter(extractBefore(task.str_opt1_out{j},'.png'),'pictures/');
        task.opt1_out(j,1)=str2num((tmp(1:end-1)));
        tmp=extractAfter(extractBefore(task.str_opt2_out{j},'.png'),'pictures/');
        task.opt2_out(j,1)=str2num((tmp(1:end-1)));
    end
    
    for j=1:size(task.str_blockN,1)
        try    
            task.blockN(j,1)=str2num(extractAfter(extractBefore(task.str_blockN{j},'.csv'),'blocklist/block'));
        catch 
            task.blockN(j,1)=str2num(extractAfter(extractBefore(task.str_blockN{j},'_myopia.csv'),'blocklist/block'));
        end
        
    end
    


end
